var playerUrl = '';


chrome.storage.sync.get({ playerUrl: '' }, (items) => {
    playerUrl = items.playerUrl;
});

chrome.storage.onChanged.addListener((changes, namespace) => {
    if (namespace === 'sync' && changes.playerUrl) {
        playerUrl = changes.playerUrl.newValue;
    }
});


chrome.runtime.onInstalled.addListener(() => {
    chrome.contextMenus.create({
        id: "open-in-app",
        title: "Open in YT-DLP Player",
        contexts: ["link"]
    });
});


chrome.contextMenus.onClicked.addListener((info, tab) => {
    if (info.menuItemId != "open-in-app" || !info.linkUrl) return;

    chrome.windows.create({
        incognito: true,
        url: `${playerUrl}/watch?url=${encodeURIComponent(info.linkUrl)}`,
        type: "popup",
        focused: true,
        state: "maximized"
    });
});


chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
    if (request.action != 'postCookies') return;
    const { playerUrl, documentCookies, currentWebsiteUrl } = request;

    let cookiesContent = '# Netscape HTTP Cookie File\n# This file was generated by the YT-DLP Web Player extension.\n';

    const url = new URL(currentWebsiteUrl);

    documentCookies.split('; ').forEach(cookieString => {
        const parts = cookieString.split('=');
        if (parts.length < 2) return;
        const name = decodeURIComponent(parts[0].trim());
        const value = decodeURIComponent(parts.slice(1).join('='));

        cookiesContent += [
            url.hostname,   // #domain
            'FALSE',        // #flag
            '/',            // #path
            'TRUE',         // #secure
            0,              // #expiration
            name,           // #name
            value           // #value
        ].join('\t') + '\n';
    });

    fetch(`${playerUrl}/cookies?url=${encodeURIComponent(currentWebsiteUrl)}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: `cookies=${encodeURIComponent(cookiesContent)}`
    })
    return true;
});
