chrome.runtime.onInstalled.addListener(() => {
  chrome.contextMenus.create({
    id: "open-in-app",
    title: "Open in YT-DLP Player",
    contexts: ["link"]
  });
});

var urlBase = 'localhost';

// Initial load of iframeBaseUrl from storage
chrome.storage.sync.get({ iframeBaseUrl: '' }, (items) => {
    urlBase = items.iframeBaseUrl;
});

// Listen for changes in storage (e.g., from options page)
chrome.storage.onChanged.addListener((changes, namespace) => {
    if (namespace === 'sync' && changes.iframeBaseUrl) {
        urlBase = changes.iframeBaseUrl.newValue;
    }
});

chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
    if (request.action === 'postNetscapeCookies') {
        const { iframeBaseUrl, documentCookies, currentWebsiteUrl } = request;
        
        if (!iframeBaseUrl) {
            console.warn('iframeBaseUrl is not set in background script, cannot post cookies.');
            return;
        }
        if (!documentCookies) {
            // console.log('No document.cookies found for:', currentWebsiteUrl);
            return;
        }

        const iframeHostname = new URL(iframeBaseUrl).origin;
        const cookiePostUrl = `${iframeHostname}/cookies?url=${encodeURIComponent(currentWebsiteUrl)}`;

        // Netscape cookie file header
        let netscapeCookiesContent = '# Netscape HTTP Cookie File\n# This file was generated by the YT-DLP Web Player extension.\n';

        const url = new URL(currentWebsiteUrl);
        const domain = url.hostname; // Host-only domain, no leading dot for document.cookie
        const path = '/'; // Default to root path for cookies from document.cookie
        const secure = url.protocol === 'https:';
        const expiration = 0; // document.cookie does not provide expiration, treat as session cookies

        // Parse document.cookie string
        documentCookies.split('; ').forEach(cookieString => {
            const parts = cookieString.split('=');
            if (parts.length < 2) return; // Skip malformed cookie strings
            const name = decodeURIComponent(parts[0].trim());
            const value = decodeURIComponent(parts.slice(1).join('=')); // Handle cases where value itself contains '='

            netscapeCookiesContent += [
                domain,         // #domain (document.cookie is host-only, no leading dot)
                'FALSE',        // #flag (host-only)
                path,           // #path
                secure ? 'TRUE' : 'FALSE', // #secure
                expiration,     // #expiration
                name,           // #name
                value           // #value
            ].join('\t') + '\n';
        });

        // console.log("Netscape Cookies:", netscapeCookiesContent);

        fetch(cookiePostUrl, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded'
            },
            body: `cookies=${encodeURIComponent(netscapeCookiesContent)}`
        })
        .then(response => {
            if (!response.ok) {
                // console.error(`Failed to post Netscape cookies. Status: ${response.status}`);
            } else {
                // console.log('Netscape cookies posted successfully.');
            }
        })
        .catch(error => {
            console.error('Error posting Netscape cookies:', error);
        });
        
        return true; // Indicate that sendResponse will be called asynchronously
    }
});

chrome.contextMenus.onClicked.addListener((info, tab) => {
  if (info.menuItemId === "open-in-app" && info.linkUrl) {
    const targetUrl = urlBase + '/watch?url=' + encodeURIComponent(info.linkUrl);
    
    // Open in NEW INCOGNITO WINDOW
    chrome.windows.create({
      incognito: true,
      url: targetUrl,
      type: "popup",
      focused: true,
      state: "maximized"
    });
  }
});

