services:
    ytdlp_web_player:
        # build: .
        image: matszwe02/ytdlp_web_player
        restart: unless-stopped
        environment:
            - APP_TITLE=YT-DLP Player
            - THEME_COLOR=#ff7300
            - GENERATE_SPRITE_BELOW=1800 # video length in seconds
            - AMOLED_BG=false
            - MAX_VIDEO_AGE=3600 # video will be removed after inactivity, in seconds
            - MAX_VIDEO_DURATION=36000
            - DEFAULT_QUALITY=720
            - LOAD_DEFAULT_QUALITY=true
            - PLAYLIST_SUPPORT=false
            - DOWNLOAD_PATH=./download
        ports:
            - 5000:5000



################################################################################
#     # Uncomment this section to enable daily updates.
#     watchtower:
#         image: nickfedor/watchtower
#         volumes:
#             - /var/run/docker.sock:/var/run/docker.sock
################################################################################



################################################################################
#     # Uncomment this section to open HTTPS under port 5001
#     nginx:
#         image: valian/docker-nginx-auto-ssl
#         restart: on-failure
#         ports:
#             - 5001:443
#         volumes:
#             - ./.ssl:/etc/resty-auto-ssl
#         environment:
#             ALLOWED_DOMAINS: 'localhost'
#             SITES: 'localhost=ytdlp_web_player:5000'
################################################################################