services:
    ytdlp_web_player:
        # build:
        #     context: .
        #     dockerfile: Dockerfile.hwaccel  # Uncomment for hardware acceleration
        image: matszwe02/ytdlp_web_player:stable
        # gpus: all
        # volumes:
        #     - ./src/cookies.txt:/app/cookies.txt
        restart: unless-stopped
        # env_file:
        #     - src/.env
        ports:
            - 5000:5000



################################################################################
#     # Uncomment this section to enable daily updates.
#     watchtower:
#         image: nickfedor/watchtower
#         volumes:
#             - /var/run/docker.sock:/var/run/docker.sock
################################################################################