name: Build App

on:
  release:
    types: [published]
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, ubuntu-22.04-arm]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '26'

    - name: Install ffmpeg
      if: ${{ matrix.os == 'ubuntu-22.04-arm' || matrix.os == 'ubuntu-22.04' }}
      run: |
        sudo apt update && sudo apt install -y ffmpeg

    - name: Apply Release Version
      id: apply_release_version
      run: |
        if [[ "${{ github.event_name }}" == "release" ]]; then
          echo "APP_VERSION=${{ github.event.release.tag_name }}"
          echo "APP_VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
        else
          echo "APP_VERSION=" >> $GITHUB_OUTPUT
        fi

    - name: Build application
      working-directory: app
      run: |
        python build_app.py "${{ steps.apply_release_version.outputs.APP_VERSION }}"

    - name: Upload linux arm
      if: ${{ matrix.os == 'ubuntu-22.04-arm' }}
      uses: actions/upload-artifact@v4
      with:
        name: linux-arm64
        path: dist/
        if-no-files-found: ignore

    - name: Upload linux x64
      if: ${{ matrix.os == 'ubuntu-22.04' }}
      uses: actions/upload-artifact@v4
      with:
        name: linux-x64
        path: dist/
        if-no-files-found: ignore

    - name: Upload windows
      if: ${{ matrix.os == 'windows-latest' }}
      uses: actions/upload-artifact@v4
      with:
        name: windows-x64
        path: dist/
        if-no-files-found: ignore

  release:
    if: ${{ github.event_name == 'release' }}
    needs: build
    runs-on: ubuntu-22.04

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/linux-x64/*
            artifacts/linux-arm64/*
            artifacts/windows-x64/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
