name: Publish Extensions
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Apply Release Version
        run: |
          RELEASE_VERSION="${{ github.event.release.tag_name }}"
          echo "Setting extension release version to ${RELEASE_VERSION#v}"
          sed -i "s/\"version\": \"1.0.0\"/\"version\": \"${RELEASE_VERSION#v}\"/" extension/manifest.json

      - name: Archive Extension
        run: |
          cd extension
          zip -r ../extension.zip .

      - name: Publish to Chrome Web Store
        id: publish-chrome-extension
        uses: puzzlers-labs/chrome-webstore-publish@v1
        with:
          mode: publish
          extension_id: ${{ vars.CHROME_EXTENSION_ID }}
          zip_file_path: ./extension.zip
          client_id: ${{ secrets.GOOGLE_CLIENT_ID }}
          client_secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          refresh_token: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          publish_target: public
          expedited_review: true

      - name: Publish to Firefox Add-ons
        uses: wdzeng/firefox-addon@v1
        with:
          addon-guid: ytdlp-web-player@matszwe02
          xpi-path: ./extension.zip
          self-hosted: false
          jwt-issuer: ${{ secrets.FIREFOX_JWT_ISSUER }}
          jwt-secret: ${{ secrets.FIREFOX_JWT_SECRET }}
